# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      displayName: Node install
      inputs:
       versionSpec: '12.x'
    - script: |
        npm install
        npm run build
      displayName: 'NPM install and build'
      workingDirectory: '$(Build.SourcesDirectory)'
    - script: npm install node-curl-cli -g
      displayName: 'Install curl'

- stage: Test
  jobs:
  - job: StartVirtualService
    displayName: StartVirtualService
    steps:
    - script: curl -o virtserver-cli-1.10.0.jar https://dl.eviware.com/virtserver/virtserver-cli-1.10.0.jar
      displayName: 'Get VirtServer Jar'
    - script: java -jar ./virtserver-cli-1.10.0.jar -login -s  https://18.224.146.21:9090 -u $(VirtServerUsername) -pw $(VirtServerPassword)
      displayName: 'Log in to VirtServer'
    - script: java -jar ./virtserver-cli-1.10.0.jar -startwt "adoVirtService" -s https://18.224.146.21:9090
      displayName: 'Start VirtServer'

  - job: ValidateSwaggerHub
    displayName: Validate SwaggerHub API
    dependsOn: StartVirtualService
    steps:
    - script: npm install swaggerhub-cli -g
      displayName: 'Install SwaggerHub CLI'
    - script: swaggerhub api:get Demo_DR1/Banking-API/1.0.0
      displayName: 'Get API from SwaggerHub using CLI'
    - script: swaggerhub api:get Demo_DR1/Banking-API/1.0.0
      displayName: 'Validate API vis SwaggerHub CLI'

  - job: RunTests
    displayName: Run ReadyAPU Tests via TestEngine
    dependsOn: ValidateSwaggerHub
    steps:
    - script: npm install testengine-cli-g
      displayName: 'Install TestEngine CLI'
    - script: testengine -u $(TEUsername) -p $(TEPassword) -H http://3.129.173.1:8080 run project $(Build.SourcesDirectory)
      displayName: 'Execute tests via TestEngine CLI'
  
  - job: StopVirtualService
    dependsOn: RunTests
    displayName: Stop Virtual Service
    steps:
    - script: curl -o virtserver-cli-1.10.0.jar https://dl.eviware.com/virtserver/virtserver-cli-1.10.0.jar
      displayName: 'Get VirtServer Jar'
    - script: java -jar ./virtserver-cli-1.10.0.jar -login -s  https://18.224.146.21:9090 -u $(VirtServerUsername) -pw $(VirtServerPassword)
      displayName: 'Log in to VirtServer'
    - script: java -jar ./virtserver-cli-1.10.0.jar -stopwt "adoVirtService" -s https://18.224.146.21:9090
      displayName: 'Stop VirtServer'

- stage: Publish
  jobs:
  - job: PublishAPI
    displayName: Publish SwaggerHub API
    steps:
    - script: npm install swaggerhub-cli -g
      displayName: 'Install SwaggerHub CLI'
    - script: swaggerhub api:publish Demo_DR1/Banking-API/1.0.0
      displayName: 'Publish SwaggerHub API'
    - script: swaggerhub api:setdefault Demo_DR1/Banking-API/1.0.0
      displayName: 'Set SwaggerHub API as Default'  
